# Arduino Due uses SAM3X8E SAM chip
BOARD_TAG = arduino_due_x
ARCHITECTURE = sam


# PROJECT_DIR = /Users/cwai_13/Library/Mobile\ Documents/com~apple~CloudDocs/compiler/Arduino-Makefile-master/examples/DueBlink
# #Global in .zshrc
# ARDUINO_DIR := $(HOME)/Applications/Arduino.app/Contents/Java
# ARDMK_DIR := $(HOME)/Library/Mobile\ Documents/com~apple~CloudDocs/compiler/Arduino-Makefile-master
# ARDUINO_PACKAGE_DIR := $(HOME)/Library/Arduino15/packages



# Define ARM toolchain dir if not using Arduino supplied
#ARM_TOOLS_DIR = /usr

# Define AVR toolchain dir if not using Arduino supplied and using native port
#AVR_TOOLS_DIR = /usr

# Define Arduino support package installation path where SAM device support has been installed
# Linux
#ARDUINO_PACKAGE_DIR := $(HOME)/.arduino15/packages
# macOS
#ARDUINO_PACKAGE_DIR := $(HOME)/Library/Arduino15/packages
# Windows
#ARDUINO_PACKAGE_DIR := "C:/Users/$(USER)/AppData/Local/Arduino15/packages"


include $(ARDMK_DIR)/Sam.mk
